# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("A", "Classified Deep Moonquake"),
                            ("M", "Unclassified Deep Moonquake"),
                            ("C", "Meteoroid Impact"),
                            ("H", "Shallow Moonquake"),
                            ("Z", "Mostly Short Period Event"),
                            ("L", "Lm Impact"),
                            ("S", "SIVB"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.TextField(
                        blank=True,
                        choices=[("A", "High"), ("B", "Medium"), ("C", "Low")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("data_1", models.FloatField(blank=True, null=True)),
                ("data_2", models.FloatField(blank=True, null=True)),
                ("data_3", models.FloatField(blank=True, null=True)),
                ("data_4", models.FloatField(blank=True, null=True)),
                (
                    "data_quality_1",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No Data"),
                            (2, "Noisy Data"),
                            (3, "Masked By Anoter Event"),
                            (4, "Compressed Plot Is Clipped"),
                            (5, "See Comments"),
                            (6, "Computer Generated Time"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "data_quality_2",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No Data"),
                            (2, "Noisy Data"),
                            (3, "Masked By Anoter Event"),
                            (4, "Compressed Plot Is Clipped"),
                            (5, "See Comments"),
                            (6, "Computer Generated Time"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "data_quality_3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No Data"),
                            (2, "Noisy Data"),
                            (3, "Masked By Anoter Event"),
                            (4, "Compressed Plot Is Clipped"),
                            (5, "See Comments"),
                            (6, "Computer Generated Time"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "data_quality_4",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No Data"),
                            (2, "Noisy Data"),
                            (3, "Masked By Anoter Event"),
                            (4, "Compressed Plot Is Clipped"),
                            (5, "See Comments"),
                            (6, "Computer Generated Time"),
                        ],
                        null=True,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=150, null=True)),
                ("cluster_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
