# Generated by Django 4.1.1 on 2022-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("site", models.CharField(max_length=3)),
                ("channel", models.CharField(max_length=3)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("A", "Classified Deep Moonquake"),
                    ("M", "Unclassified Deep Moonquake"),
                    ("C", "Meteoroid Impact"),
                    ("H", "Shallow Moonquake"),
                    ("Z", "Short Period Event"),
                    ("L", "Lm Impact"),
                    ("S", "Sivb"),
                    ("U", "Unclassified"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
